language: java
ant test
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7
  
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
